### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by FelipePhilippCbh** [JohnTheGr8/Flow.Plugin.Github#8]
Hi, thanks for writing the extension!

Does the search work on private repositories in an organization? This doesn't work for me and I want to double check.

**Comment by JohnTheGr8** [comment]
Hello. If your access token has `repo` access, your private repositories should show up when you type something like:

```
gh FelipePhilippCbh/
```

A shorter syntax for _own_ repos has been suggested in #6 but I have been too swamped to get to it... :worried:

**Comment by FelipePhilippCbh** [comment]
That works, I guess it was some cache on my end. Thanks!
