### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by rafstahelin** [JohnTheGr8/Flow.Plugin.Github#9]
using your plugin get fail

![image](https://github.com/user-attachments/assets/c4c1745d-4889-41e4-9c5f-02f66ce894ec)
![image](https://github.com/user-attachments/assets/48084ed3-9157-4501-bc81-8a905487d97b)

How can i fix it?

**Comment by JohnTheGr8** [comment]
Seems identical to #7. 

Are you running the latest version of the plugin? I cannot reproduce with plugin version 1.3.1
